// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[CreateProjectError-1000]
	_ = x[UpdateProjectError-1001]
	_ = x[DeleteProjectError-1002]
}

const (
	_ErrorCode_name_0 = "OK"
	_ErrorCode_name_1 = "CreateProjectErrorUpdateProjectErrorDeleteProjectError"
)

var (
	_ErrorCode_index_1 = [...]uint8{0, 18, 36, 54}
)

func (i ErrorCode) String() string {
	switch {
	case i == 0:
		return _ErrorCode_name_0
	case 1000 <= i && i <= 1002:
		i -= 1000
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
